import { StyleSheet } from "react-native";

export default StyleSheet.create({
  flex: { flex: 1 },
  scrollContent: { flexGrow: 0 },

  heroHeader: {
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 28,
    overflow: "hidden",
  },
  heroBubble1: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(255,255,255,0.07)",
    top: -80,
    right: -50,
  },
  heroBubble2: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.05)",
    bottom: -20,
    left: -30,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnText: { fontSize: 20, color: "#fff", fontWeight: "400" },
  heroTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#ffffff",
    flex: 1,
    textAlign: "center",
  },
  heroDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginBottom: 16,
  },
  heroTextBlock: { alignItems: "center" },
  heroSubtitle: {
    fontSize: 15,
    color: "rgba(255,255,255,0.95)",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 4,
  },
  heroCompany: {
    fontSize: 13,
    color: "rgba(255,255,255,0.65)",
    textAlign: "center",
    marginBottom: 8,
  },

  formCard: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -20,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 16,
  },
  fieldGroup: { marginBottom: 20 },
  fieldLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  input: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontSize: 15,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 14,
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 6,
    marginLeft: 2,
    fontWeight: "500",
  },
  submitBtn: {
    paddingVertical: 16,
    borderRadius: 16,
    marginTop: 4,
    marginBottom: 8,
    alignItems: "center",
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  submitBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.3,
  },
});