import { StyleSheet } from "react-native";

export const lightTheme = {
  background: "#F3F4F6",
  card: "#ffffff",
  cardBorder: "#E5E7EB",
  title: "#111827",
  subtitle: "#6B7280",
  muted: "#9CA3AF",
  salary: "#2563EB",
  input: "#ffffff",
  inputText: "#111827",
  inputPlaceholder: "#9CA3AF",
  saveBtn: "#374151",
  applyBtn: "#2563EB",
  headerBg: "#2563EB",
  fallbackLogoBg: "#DBEAFE",
  fallbackLogoText: "#2563EB",
  fallbackLogoBorder: "#BFDBFE",
  logoBorder: "#E5E7EB",
  logoBg: "#F3F4F6",
  emptyText: "#9CA3AF",
  tagBg: "#EFF6FF",
  tagBorder: "#BFDBFE",
  tagText: "#2563EB",
};

export const darkTheme = {
  background: "#0F172A",
  card: "#1E293B",
  cardBorder: "#334155",
  title: "#F1F5F9",
  subtitle: "#94A3B8",
  muted: "#64748B",
  salary: "#60A5FA",
  input: "#1E293B",
  inputText: "#F1F5F9",
  inputPlaceholder: "#64748B",
  saveBtn: "#475569",
  applyBtn: "#2563EB",
  headerBg: "#1E3A5F",
  fallbackLogoBg: "#1E3A5F",
  fallbackLogoText: "#60A5FA",
  fallbackLogoBorder: "#2563EB",
  logoBorder: "#334155",
  logoBg: "#0F172A",
  emptyText: "#64748B",
  tagBg: "#1E3A5F",
  tagBorder: "#2563EB",
  tagText: "#60A5FA",
};

export type Theme = typeof lightTheme;

export default StyleSheet.create({
  card: {
    padding: 18,
    marginVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  companyLogo: {
    width: 48,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
  },
  companyLogoFallback: {
    width: 48,
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  companyLogoFallbackText: {
    fontSize: 20,
    fontWeight: "700",
  },
  cardHeaderText: {
    flex: 1,
  },
  title: {
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 2,
  },
  companyName: {
    fontSize: 14,
  },
  salaryLocationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  salaryText: {
    fontSize: 14,
    fontWeight: "600",
  },
  locationText: {
    fontSize: 13,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
  },
  button: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
    fontSize: 15,
  },
  searchInput: {
    borderWidth: 0,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
});