import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1 },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "rgba(255,255,255,0.80)",
    marginTop: 2,
  },
  container: { flex: 1, borderTopLeftRadius: 24, borderTopRightRadius: 24, marginTop: -12 },
  listContent: { padding: 16, paddingTop: 16 },
  card: {
    padding: 18,
    marginBottom: 12,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  companyLogo: {
    width: 48,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
  },
  companyLogoFallback: {
    width: 48,
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  companyLogoFallbackText: {
    fontSize: 20,
    fontWeight: "700",
  },
  cardHeaderText: { flex: 1 },
  title: { fontWeight: "700", fontSize: 17, marginBottom: 2 },
  companyName: { fontSize: 14 },
  buttonRow: { flexDirection: "row", gap: 10 },
  button: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "#fff", textAlign: "center", fontWeight: "600", fontSize: 15 },
  emptyText: { textAlign: "center", marginTop: 80, fontSize: 16 },
});